FORMAT: 1A
HOST: http://api.mydigitalme.com/

# mydigitalme

MyDigitalMe is a collector for all your digital assets spread across the digital world
## Your digital representation [/me]

### Get Me [GET]

+ Response 200 (application/json)

    + Attributes (Me)

### Create Me  [POST]

You may want to create your own!

+ Request (application/json)

    + Attributes (Me)

+ Response 201 (application/json)

    + Headers

            Location: /me

            
## Data Structures

### Me (object)
+ first_name: Your First Name
+ last_name: Your Last Name
+ public_alias: Your known personal and unique alias to the world